import enum


class Seccion(enum.Enum):
    DESTACADOS = "destacados"
    NOVELAS = "novelas"
    PROGRAMAS = "programas"
    CINE = "cine"
    AMAS = "amas"
    SERIES = "series"
    KIDSIETE = "kidsiete"
    ESMUCHOMAS = "esmuchomas"
    REALITIES = "REALITIES"


class Screen(enum.Enum):
    WEBVIEW = "WEBVIEW"
    VIEW = "VIEW"


class AuthLevel(enum.Enum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"


class Action(enum.Enum):
    NAVIGATE = "NAVIGATE"
    PLAY_VIDEO = "OPEN_WEB_VIEW"
    OPEN_WEB_VIEW = "OPEN_WEB_VIEW"
    NONE = "NONE"


class Component(enum.Enum):
    CONTAINER = "CONTAINER"
    CHILD = "CHILD"
    # BOTON QUE OCUPA EL ANCHO DE LA PANTALLA Y SE USA PARA VOTAR POR UN PARTICIPANTE FAVORITO
    ONPRESS_BUTTON = "ONPRESS_BUTTON"
    CARD_EXPANDED = "ONPRESS_BUTTON"  # CARD QUE APARECE EN LA SECCION DE INTERACTUA
    # LISTOADO VERTICAL SCROLLABLE DE EPISODIOS DISPONIBLES
    VERTICAL_CHAPTERS = "VERTICAL_CHAPTERS"
    CARROUSEL_HORIZONTAL_LANDSCAPE = "CARROUSEL_HORIZONTAL_LANDSCAPE"
    CARROUSEL_HORIZONTAL_PORTRAIT = "CARROUSEL_HORIZONTAL_PORTRAIT"
    CARROUSEL_HORIZONTAL_CUADRADO = "CARROUSEL_HORIZONTAL_CUADRADO"
    CARROUSEL_HORIZONTAL_CHARACTERS = "CARROUSEL_HORIZONTAL_CHARACTERS"
    ADS_CONTAINER = "ADS_CONTAINER"
    CARROUSEL_HORIZONTAL_LIVE = "CARROUSEL_HORIZONTAL_LIVE"
    BANNER_EXPANDED = "BANNER_EXPANDED"
    BANNER_PRINCIPAL = "BANNER_PRINCIPAL"
    CARROUSEL_PORTRAIT_LARGE = "CARROUSEL_PORTRAIT_LARGE"
    DESCRIPTION_SECTION = "DESCRIPTION_SECTION"  # NO ESTOY SEGURO AUN
    CARROUSEL_HORIZONTAL_LANDSCAPE_WITH_ACTION = "CARROUSEL_HORIZONTAL_LANDSCAPE_WITH_ACTION"
